spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=appsecret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=5RUJ6r1CsDwthbFTHTrtqKE0h4YaKvzQjORzNDqJl+LQz1PV57XIBhAhxaLd0Qmn3T3E/73vAEV83CZv1lr+VA==
app.jwt.access-minutes=30
app.jwt.refresh-days=7
