spring.application.name=fiados-service
server.port=8090

spring.datasource.url=jdbc:h2:mem:fiadosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


##conexion a la clave de firebase

firebase.credentials-path=/home/toto/.secrets/firebase/claveMicroServicioFiados.json
